language: php

php:
 - 5.5
 - 5.6
 - 7.0
 - hhvm

sudo: false

matrix:
  fast_finish: true
  include:
  - php: 5.5
    env: |
      COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
      PHPUNIT_COVERAGE='--coverage-text --coverage-clover=coverage.clover'
  - php: 5.6
    env: SYMFONY_VERSION="2.7.*"
  - php: 5.6
    env: SYMFONY_VERSION="2.8.*"
  allow_failures:
  - php: hhvm

install:
  - if [ "${COVERAGE}" = "" ]; then phpenv config-rm xdebug.ini; fi;
  - travis_retry wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar

before_script:
  - if [ "${SYMFONY_VERSION}" != "" ]; then composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update; fi
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction;

script:
  - vendor/bin/phpunit ${PHPUNIT_COVERAGE}
  - php php-cs-fixer.phar fix src/ --level=psr2 --dry-run

after_script:
  - if [ "${PHPUNIT_COVERAGE}" != "" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "${PHPUNIT_COVERAGE}" != "" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;

cache:
  directories:
  - $HOME/.composer/
