services:
  boekkooi.doctrine_jack.discriminator_map.listener:
    class: Boekkooi\Bundle\DoctrineJackBundle\EventListener\DiscriminatorMapListener
    arguments:
      - '%boekkooi.doctrine_jack.discriminator_map.mapping%'
      - '@annotation_reader'
    tags:
      - { name: doctrine.event_subscriber }
